version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: lunch-tracker-db
    environment:
      POSTGRES_DB: lunch_tracker
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: very_hard_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U app_user -d lunch_tracker']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
